name: Deploy Next.js application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t vaibhav805/next_portfolio .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to docker hub
        run: docker push vaibhav805/next_portfolio:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull vaibhav805/next_portfolio:latest
      - name: Delete old container
        run: sudo docker rm -f next_portfolio
      - name: Run docker container
        run: sudo docker run -d -p 3000:3000 --name next_portfolio vaibhav805/next_portfolio:latest